baseurl = "https://dittastory28.netlify.app/"
googleAnalytics = "G-HHRW66DYFY"
languageCode = "en-us"
languageLang = "en"
title = "Ditta Story "
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
images = ["img/og-image.jpg"]
