baseurl = "https://dittalyona28.github.io/ditta-story/"
languageCode = "en-us"
languageLang = "en"
title = "Ditta Story "
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
google_analytics_id = "G-HHRW66DYFY"
images = ["img/og-image.jpg"]
